### PR TITLE
change regex to match the default status-log format currently used by openvpn 2.4 on ArchLinux

### PR DESCRIPTION
**Pull request by philipflohr**
this addresses #9

### CODE REVIEW

**Comment by philipflohr** [comment]
the format on arch is
HEADER,CLIENT_LIST,Common Name,Real Address,Virtual Address,Virtual IPv6 Address,Bytes Received,Bytes Sent,Connected Since,Connected Since (time_t),Username,Client ID,Peer ID

I'll try to create the used regex from the status file format announcement

**Comment by AuspeXeu** [comment]
Cool. Let me know how it goes. How do the rows in this format look like?
Can you provide an example?

**Comment by AuspeXeu** [comment]
Maybe the regex needs to dynamic with respect to the header line?

**Comment by philipflohr** [comment]
I'm working on exactly that.
Currently this is unfinished, I'll let you know once this is ready.

Do you know how virtual ipv6 addresses are shown on debian?

**Comment by AuspeXeu** [comment]
The format I get is this

```
OpenVPN CLIENT LIST
Updated,Thu Feb  1 11:38:11 2018
Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
[...]
ROUTING TABLE
Virtual Address,Common Name,Real Address,Last Ref
[...]
GLOBAL STATS
Max bcast/mcast queue length,1
END
```

**Comment by philipflohr** [comment]
Can you provide a header example line of a debian server?

**Comment by AuspeXeu** [comment]
I pasted it above already...

**Comment by philipflohr** [comment]
Is there no HEADER line which announces the log format?

**Comment by AuspeXeu** [comment]
This is the full content of the file without the peers ofc...

**Comment by philipflohr** [comment]
The regex construction and entry value extraction is now handled per server / logfile.
Everything works on archlinux and the compatibility to the debian log should ok (Your regex is used if there is no header line detected in the logfile). Could you test if this is still working?

**Comment by AuspeXeu** [comment]
Closing this in favour of the latest version using `client-connect` and `client-disconnect` hooks.

**Pull request closed without merging**
