### PR TITLE
Moving away from scripts to the management interface

### PR DESCRIPTION
**Pull request by AuspeXeu**

### CODE REVIEW

**Comment by xinthose** [comment]
How does this work now?  Why the change?

**Comment by AuspeXeu** [comment]
The management interface is accessed through telnet. I decided to migrate to this since it gives more options to interact with the connected clients (for example disconnect them) and also obtain other information such as data traffic statistics. The updated setup procedure can be found in the readme.

**Comment by xinthose** [comment]
OK.  Thank you.

**Comment by AuspeXeu** [comment]
Let me know if you run into any problems.

**Pull request merged**
