### PR TITLE
add `date_format` option to `cfg.json`

### PR DESCRIPTION
**Pull request by xinthose**
2nd try.  `date_format` is not a part of the `servers` object in `cfg.json` anymore.  I still need to test this at work, but the commands `npm run build` and `node server.js` work.

### CODE REVIEW

**Comment by AuspeXeu** [comment]
Actually, could you check whether the import of the config file exposes the data inside it to the frontend?

**Comment by xinthose** [comment]
I will test this PR on the 31st at work.  

> 
> 
> Actually, could you check whether the import of the config file exposes the data inside it to the frontend?

Is this undesirable?  I assume that vue would compile the JSON into JavaScript.

**Comment by xinthose** [comment]
OK.  In my use case, I access the status webpage by the computer domain name on our intranet, so exposing the IP of the VPN server does not matter to me a great deal.  The server IP's will show in `/dist/js/app.69b10e5e.js` with the import line but do not show without it.  I do not understand why if the javascript is loading `cgf.json` in `util.js`.

Let me know if you have a better idea for my simple objective.

**Comment by AuspeXeu** [comment]
Off the top of my head I would say, we need a separate config file for UI parameters or a parameter at compile time (`npm run build`). The former seems cleaner to me, thoughts?

**Comment by xinthose** [comment]
OK.  I add `cft.json` in the `public` directory.  That seems simple enough.  It could grow in the future.

**Pull request closed without merging**
